language: bash
services: docker
env:
  - VERSION=5.11.1
  - VERSION=5.12.0
  - VERSION=6.11.0
  - VERSION=8.1.3
  - VERSION=8.8.0
before_script:
- env | sort
- cd "$VERSION"
- image="silvervue/debian:$VERSION"
script:
- travis_retry docker build -t "$image" .
after_script:
- docker images
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD";
  docker push "$image";
  fi